apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store
  namespace: genai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
  # For larger GPU models consider GKE Filestore / GCS FUSE instead.
