apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-embedding
  namespace: genai
  labels:
    app: serving-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serving-embedding
  template:
    metadata:
      labels:
        app: serving-embedding
    spec:
      containers:
        - name: embedding
          image: ghcr.io/huggingface/text-embeddings-inference:1.5
          args:
            - --model-id
            - BAAI/bge-small-en-v1.5
            - --port
            - "8001"
          ports:
            - name: http
              containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              memory: 4Gi